export enum TipoTransmissaoEnum {
  CAUSA_MORTIS = 1,
  CESSAO_DIREITOS_HEREDITARIOS = 2,
  DOACAO_RESERVA_USUFRUTO = 3,
  DOACAO_PLENA = 4,
  EXCEDENTE_MEACAO = 5,
  EXTINCAO_RENUNCIA_USUFRUTO = 6,
  INSTITUICAO_USUFRUTO = 7,
  DOACAO_NUMERARIO = 8,
}
